### ISSUE TITLE
Create and support a PPA

### ISSUE THREAD

**Issue by Diagoras** [AdoptOpenJDK/openjdk-installer#10]
It looks like AdoptOpenJDK offers downloads from its website of JDK releases, and also offers a Homebrew tap for command line installation. However, I haven't been able to find a PPA that provides releases of AdoptOpenJDK binaries. Does one already exist, and if not then how about creating one for easy installation on Ubuntu servers?

FWIW, this issue is probably dependent on https://github.com/AdoptOpenJDK/openjdk-build/issues/458, since it'd be difficult to have a PPA if AdoptOpenJDK isn't offered as a DEB first! ;)

**Comment by rpardini** [comment]
Hi, check out https://github.com/rpardini/adoptopenjdk-deb-installer 
It's an effort to build Debian/Ubuntu installer packages via a generator that consumes the AdoptOpenJDK API. Ubuntu packages for testing are available at a Launchpad PPA already. 
I would love to contribute this to AdoptOpenJDK if you're interested. Let me know...

**Comment by karianna** [comment]
@rpardini That would be great - I see we're setting up a call to discuss.  But in principle a PR here is welcome.

**Comment by tresf** [comment]
webupd8team has a wrapper script they offer for the Oracle tarball.  A similar approach might be a good starting point (instead of an all-inclusive `.deb`).  I've used webupd8team on many Ubuntu machines.

**Comment by rpardini** [comment]
@tresf https://github.com/rpardini/adoptopenjdk-deb-installer is actually based on and credits webupd8team's work; it could be adequate if you're looking to migrate from those packages, since it does mostly the same stuff (eg config in /etc, bringing in fonts and all x11 deps, fulfilling `default-jre` and others, etc). it does co-exist with oracle's, and the `-set-default` variant of the packages helps to switch. you still need to restart java-using services manually though to use updated `/usr/bin/java` alternative symlink.

**Comment by gdams** [comment]
Closing as this is now complete! check out https://medium.com/adoptopenjdk/adoptopenjdk-rpm-and-deb-files-7003ba38144e for more info!

**Comment by mauromol** [comment]
I suggest you also add instructions on how to use the PPA at: https://adoptopenjdk.net/releases.html

**Comment by karianna** [comment]
@mauromol can you open an issue on openjdk-website?

**Comment by tresf** [comment]
The link asks users to  edit a `sources.list` file, which is prone to user-error.  Would you consider changing it to use something more like this?

```bash
sudo add-apt-repository --yes https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/
```
... also, the article says to pipe the GPG  to `apt-key add -`, but most users won't be running a terminal as root.  Would you consider piping it to `sudo apt-key add -`?  i.e.:

```bash
wget -qO - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | sudo apt-key add -
```
Note, `sudo` (for systems configured with it) work from a user or root terminal.  There's no disadvantage in placing it in the documentation unless targetting a system which comes with it disabled/not installed.

**Comment by gdams** [comment]
@tresf updated thanks :)

**Comment by jefft** [comment]
It would be nice if the PPA were hosted on adoptopenjdk.net. I have no idea who jfrog.io is, nor their security practices. With tar.gz distribution I can check the SHA.

Or put another way: would AdoptOpenJDK be happy to create a GPG key, give the private key to @gdams, and publish the public key on adoptopenjdk.net?

**Comment by aahlenst** [comment]
Two of the three things you want are already the case today. The RPM packages and package indices are signed with our GPG key, George (as a TSC member) has it.

I don't see the advantage in the other things you want. You'd trade JFrog (plus AWS) with GitHub (plus AWS), because the website as well as the binary releases are hosted on GitHub. If we'd host Artifactory ourselves, you'd trade JFrog (plus AWS) with an overworked AdoptOpenJDK community member (me) and some cloud provider. 

Besides, with the binary releases, you're worse off because the fingerprints aren't signed.

If you want to discuss this issue further, please open a new issue.

**Comment by overheadhunter** [comment]
Ubuntu's OpenJDK builds have some issues, which is why I want to use AdoptOpenJDK builds that work just fine. I need it as a build dependency on my own PPA. However this seems to be impossible at the moment.

Today we have two things:
- the repo on bintray containing the actual _packages_
- @rpardini's PPA giving us _installers_ that download those pre-built packages

Neither of which can be used as an upstream dependency during PPA builds, because PPA builds a) can only depend on packages in Ubuntu's main repo or other PPAs and b) have to run completely isolated without the option to download stuff (which is why @rpardini's solution doesn't work for me).

Therefore I'd like to know if (regardless of any plans to do so) it is even technically possible to get AdoptOpenJDK to be built on the PPA build system.

**Comment by aahlenst** [comment]
@overheadhunter Maintainer of Linux packages here. Happy to talk. Could you please open a new issue? You can copy & paste your text. Or, if you want, you can include the answer to the question that I have right now: Is it possible for us the upload the pre-built packages to a PPA?
