### ISSUE TITLE
Deployment of debian release -2 not for version 11

### ISSUE THREAD

**Issue by nudgegoonies** [AdoptOpenJDK/openjdk-installer#128]
Is there some problem with the deployment of the package builds to Artifactory?

The new -2 version of AdoptOpenJDK-8 is here:
https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/pool/main/a/adoptopenjdk-8-hotspot/
But it misses the architectures other than amd64.

The new -2 version od AdoptOpenJDK-11 is missing completely:
https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/pool/main/a/adoptopenjdk-11-hotspot/

I have looked other directories and it seems to be inconsistenst too regarding architectures and debian release version.

**Comment by aahlenst** [comment]
As far as I know there's a magic script that only publishes a new release if there's a new JDK release. The case that existing packages should be re-released because of changes applied to the packaging isn't covered yet.

One possible solution: Create a daily Jenkins job that builds the packages in any case and also runs the publish task. Then let the Gradle publish task figure out if a package should actually be published (because of new version numbers) or not. 

What do you think, @gdams?

**Comment by nudgegoonies** [comment]
The debian release, actually -2, is actually persisted within the sourcecode in the git repository. When a new JDK release appears this must be reseted to -1. The same is true for rpm releases too.

**Comment by aahlenst** [comment]
Could you elaborate why we should reset the variant number? If I remember correctly, at least the Debian guidelines do not dictate a particular format or behaviour as long as the new variant comes after the last when you sort them naturally. Ubuntu for example uses variant numbers like `1ubuntu2~19.04.1`.

**Comment by nudgegoonies** [comment]
There must be a debian release starting with - but as far as i know this is not a requirement. Thus all packages i have seen have reseted the debian release to -1 after an upstream update this way:
```
1.2.3-1
1.2.3-2
1.3.0-1
```
Of course not resetting would not hurt:
```
1.2.3-1
1.2.3-2
1.3.0-3
```

**Comment by nudgegoonies** [comment]
Any news on this? I wanted to get rid of my self built packages in our own repo but the -2 is still not online for all java variants.

**Comment by nudgegoonies** [comment]
Will this work when the new 8u222, 11.0.4, 12.0.2 and 13.0.0 Versions come?

**Comment by karianna** [comment]
@gdams or @nudgegoonies Any idea?  If we need to make changes now is the time :-)

**Comment by aahlenst** [comment]
New JDK releases are never a problem, only re-releases or installer-only. Will fix as soon as I‘m out of crunch mode.

**Comment by nudgegoonies** [comment]
Thank you for the answer. Then the release is not affected. But then the decision to not reset the debian release version is taken? If yes, i could add a section in the documentation that distro build release versions increase individually and never reset to -1 also after AdoptOpenJDK version updates.

**Comment by aahlenst** [comment]
I don't want to reset the number if there aren't pressing reasons for it. Otherwise we have to add that to some pre-release checklist. So either someone overrides me or it stays that way. If you think this needs to be documented, go ahead.

**Comment by nudgegoonies** [comment]
Ok. Please excuse one last question. When will the debian-release version be increased? Immediately after a new version was deployed or before a new version will be deployed? Actually it is still -2 in the iteration variable in the deb sources from my latest MR that was merged to master. In my opinion it is better to increase it automatically during the deployment build/pipeline when it is finished. So from that time on people work on the "new" version and on a "released" version.

**Comment by aahlenst** [comment]
@nudgegoonies Just keep the questions coming.

My personal policy is to increase the version together with any change that alters the behaviour of the packages. Otherwise, there's no reason to increase the number because the packages don't change.

Examples:

* Alter release targets: No change to version because the packages don't change.
* Change contents (files added/removed etc.): Increase version because the packages change.
* Alter metadata (dependencies, descriptions etc.): Increase version because the packages change.

If I remember correctly, your change was the last that altered the packages so it's okay if the packages are still at version 2.

I might have missed something, though.

**Comment by nudgegoonies** [comment]
@aahlenst Thank you for the examples. This sounds like a a good strategy. If the old releases are safe when someone forgets to increase the version number this is completely fine. I am a build engineer and i saw so much trouble with release-build-automation like overwritten older releases or useless increments in micro-versions that i am very cautious and sensitive in that topic :)

**Comment by aahlenst** [comment]
The Artifactory user that pushes the releases (and nightly builds) does not have the necessary permissions to overwrite files. So even in case of a misconfiguration that should not happen.

Forgetting to increase version numbers or erroneously increasing them can still happen, especially if I'm at sleep at the keyboard.

**Comment by aahlenst** [comment]
This was fixed with #141.

For future reference: If it's time to re-release Linux packages, compile the necessary arguments for the Jenkins job `standalone_create_installer_linux` and open TSC issue (example: https://github.com/AdoptOpenJDK/TSC/issues/105).
