### ISSUE TITLE
jvm.dll location has changed for Windows X86-32 Hotspot from bin/server to bin/client

### ISSUE THREAD

**Issue by douph1** [AdoptOpenJDK/openjdk-installer#137]
This change is not yet taking into installer

PS: no change for openj9

This change was found by looking at pre-release 8u222 internal zip

**Comment by douph1** [comment]
I'm looking at the commit in https://github.com/AdoptOpenJDK/openjdk-build wich trigger this change, is someone can help me to find it to confirm.
I don't think it is documented somewhere in a changelog

**Comment by karianna** [comment]
@ali-ince will know

**Comment by ali-ince** [comment]
Hi @douph1,

The specific change [#1104](https://github.com/AdoptOpenJDK/openjdk-build/pull/1104), [#1113](https://github.com/AdoptOpenJDK/openjdk-build/pull/1113) and [#1114](https://github.com/AdoptOpenJDK/openjdk-build/pull/1114) are made to get `client` and `server` jvm variants into the distribution whereever it's possible. 

The change was initially done to get x86 hotspot binaries in line with other builds (due to [#871](https://github.com/AdoptOpenJDK/openjdk-build/issues/871)) but later on extended to include both x86 and x64 binaries (except for JDK8 x64 where `client` variant is not supported).

The change has the following consequences;

| Version | Configuration | Included Variants |
| :--- | :--- | :--- |
| Java 8 | JDK x86 | `jre/bin/client/jvm.dll` and `jre/bin/server/jvm.dll`  | 
| | JRE x86 | `bin/client/jvm.dll`  |
| | JDK x64 | `jre/bin/server/jvm.dll`  |
| | JRE x64 | `bin/server/jvm.dll`  |
| Java 11 | JDK x86 | `bin/client/jvm.dll` and `bin/server/jvm.dll`  | 
| | JRE x86 | `bin/client/jvm.dll` and `bin/server/jvm.dll`  |
| | JDK x64 | `bin/client/jvm.dll` and `bin/server/jvm.dll`  |
| | JRE x64 | `bin/client/jvm.dll` and `bin/server/jvm.dll`  |
| Java 12 | JDK x86 | `bin/client/jvm.dll` and `bin/server/jvm.dll`  | 
| | JRE x86 | `bin/client/jvm.dll` and `bin/server/jvm.dll`  |
| | JDK x64 | `bin/client/jvm.dll` and `bin/server/jvm.dll`  |
| | JRE x64 | `bin/client/jvm.dll` and `bin/server/jvm.dll`  |

As a summary; all JDK and JRE binaries for JDK 11 and 12 are same and contain both `client` and `server` variants. For JDK 8, it's a bit out of order as can be seen in the table.

I hope this gives you a better picture of the change.

As a suggestion, I think it might be wise to default to `server/jvm.dll` for `RuntimeLib` registry value if corresponding file is present and to `client/jvm.dll` otherwise. What do you think?

**Comment by douph1** [comment]
I think the goal is to be aligned with Oracle default RuntimeLib path, but I don't know wich one they pointed for each configuration ..

And @ali-ince do you know if there is any change on OpenJ9 too ?
if we must set RuntimeLib for OpenJ9 too .. ?

>default to server/jvm.dll for RuntimeLib registry value if corresponding file is present and to client/jvm.dll otherwise

**Comment by JScheiterbauer** [comment]
Hi all!
Does this issue block the release of 8u222?
It should have been published yesterday and I'm waiting eagerly for it :-)

Also:
I've seen that the Windows 64 builds don't have client.dlls, is there a special reason for it?

**Comment by karianna** [comment]
We'll discuss today how much of a blocker this is in the release channel in the adoptopenjdk slack.

**Comment by JScheiterbauer** [comment]
can you estimate how long the release of 8u222 will be delayed?

**Comment by ali-ince** [comment]
@douph1 No changes applied to OpenJ9. I don't have that much knowledge about OpenJ9 part of things so I think I might skip that question about whether to have that registry value for OpenJ9 or not.

**Comment by karianna** [comment]
I've started a live conversation in the #installer channel on our slack.

**Comment by douph1** [comment]
| Hotspot Version | Configuration | Included Variants  |Oracle dll path in RuntimeLib |
| :--- | :--- | :--- | :--- |
| Java 8 | JDK x86 | `jre/bin/client/jvm.dll` and `jre/bin/server/jvm.dll`  | no RuntimeLib for private JRE (same as JRE below if Public JRE installed during setup)
| | JRE x86 | `bin/client/jvm.dll`  |jre-8u202-windows-i586.exe Java Runtime Environment `C:\Program Files (x86)\Java\jre1.8.0_202\bin\client\jvm.dll`
| | JDK x64 | `jre/bin/server/jvm.dll`  |no RuntimeLib for private JRE (same as JRE below if Public JRE installed during setup)
| | JRE x64 | `bin/server/jvm.dll`  | `C:\Program Files\Java\jre1.8.0_202\bin\server\jvm.dll`
| Java 11 | JDK x86 | `bin/client/jvm.dll` and `bin/server/jvm.dll`  | no public download anymore (jdk12 is out)
| | JRE x86 | `bin/client/jvm.dll` and `bin/server/jvm.dll`  | no public download anymore (jdk12 is out)
| | JDK x64 | `bin/client/jvm.dll` and `bin/server/jvm.dll`  | no public download anymore (jdk12 is out)
| | JRE x64 | `bin/client/jvm.dll` and `bin/server/jvm.dll`  | no public download anymore (jdk12 is out)
| Java 12 | JDK x86 | `bin/client/jvm.dll` and `bin/server/jvm.dll`  |  don't see x86 build
| | JRE x86 | `bin/client/jvm.dll` and `bin/server/jvm.dll`  | don't see x86 build
| | JDK x64 | `bin/client/jvm.dll` and `bin/server/jvm.dll`  | no RuntimeLib (dll in `bin/server/jvm.dll`
| | JRE x64 | `bin/client/jvm.dll` and `bin/server/jvm.dll`  | don't see JRE build

**Comment by douph1** [comment]
So I propose to set it for and to (only):

Java8 JRE x86 > bin/client/jvm.dll
Java8 JRE x64 -> bin/server/jvm.dll
Java11 JRE x64 ->bin/server/jvm.dll
Java12 JRE x64 ->bin/server/jvm.dll
etc
If we later drop JRE for JDK 13 etc we will stop to let RuntimeLib

**Comment by karianna** [comment]
> So I propose to set it for and to (only):
> 
> Java8 JRE x86 > bin/client/jvm.dll
> Java8 JRE x64 -> bin/server/jvm.dll
> Java11 JRE x64 ->bin/server/jvm.dll
> Java12 JRE x64 ->bin/server/jvm.dll
> etc
> If we later drop JRE for JDK 13 etc we will stop to let RuntimeLib

Sounds good to me!
