### ISSUE TITLE
Rename MSI product names to allow JDK/JRE

### ISSUE THREAD

**Issue by alexhass** [AdoptOpenJDK/openjdk-installer#16]
Need to rename some names so it is clear we are installing JDK or JRE.

Thought first we will have OpenJRE and OpenJDK, but I might me wrong. Waiting for feedback on OpenJRE name.

**Comment by karianna** [comment]
OpenJRE would be incorrect in this case.

**Comment by karianna** [comment]
Unfortunately, that's not how it works with the Trademarks / legal names around OpenJDK.

**Comment by alexhass** [comment]
Well we need self speaking names. 

Oracle names it „Java 8 Update 181 (x64)“ and „Java 8 Development Kit“. I was thinking of naming it 100% the same like Oracle, but I guess we are not allowed to name it „Java“ as Java is a trademark of Oracle isn’t it? The vendor will be AdoptOpenJDK... so the source is clear. We are not using the Java logo, too. Just the name of the programming language. Are we allowed to name the product „Java“?

Naming it „OpenJDK Java Runtime Environment“ for JRE and „OpenJDK Java Development Kit“ for JDK may work, but looks tooo long for setup dialogs. Naming it „OpenJDK JRE“ looks very confusing.

Aside can I leave the „Eclipse“ out and just name the main feature „JDK/JRE with OpenJ9“? Space is really limited...

**Comment by karianna** [comment]
Hi @alexhass - great questions!

For our hotspot based builds I think we can use "OpenJDK 8 Update 181 (x64)“ and "OpenJDK 8 Development Kit".  The vendor, as you say, is us so that's OK.

I think naming it "OpenJDK Java Runtime Environment“ for JRE and "OpenJDK Java Development Kit“ for JDK is actually OK.

There would be a strong preference to include Eclipse as the prefix (actually a legal requirement from Eclipse I'm afraid).

Hope that helps?  Appreciate this all makes your life more difficult, but we do have to be legally correct/accurate, especially as your good work will be used by a few 100,000 Java developers / users :-)

**Comment by alexhass** [comment]
Let's go with this pull for now... I have not fully compiled all versions yet. Need to wait until tomorrow as it takes 2-3 hours. Will upload them to my website in ~24 hours.
