### ISSUE TITLE
Document how to install on Windows without admin privileges

### ISSUE THREAD

**Issue by ggam** [AdoptOpenJDK/openjdk-installer#200]
From #107 it seems like it's possible to install without admin privileges, but I'm unable to do so. If it's really possible, it needs to be documented and possibly the installer should default to it (with a warning about side effects) when the currently logged in user is not admin.

**Comment by aahlenst** [comment]
It is documented. Please see https://github.com/AdoptOpenJDK/openjdk-installer/tree/master/wix#per-user-install. The problem is we're currently not doing the best job at providing accessible documentation. Maybe I find the time some day to change that.

The key here is that you have to pass arguments to msiexec using cmd or PowerShell:

```
msiexec /i OpenJDK14U-jdk_x64_windows_hotspot_14_36.msi MSIINSTALLPERUSER=1
```

This launches the interactive installer and you can use it as normal. But as stated in the README, some features are not available for a user installation.

I am not aware of a way to force the interactive installer to perform a user installation using the GUI.
