### ISSUE TITLE
Windows Program Name Changed

### ISSUE THREAD

**Issue by MarkRx** [AdoptOpenJDK/openjdk-installer#262]
The latest AdoptOpenJDK seems to have different properties which changed what the program is called in Windows Programs and Features. This causes complications for CM automation that depends on naming and versioning consistency. 

It appears to have changed with https://github.com/AdoptOpenJDK/openjdk-installer/pull/258

This may or may not be a "bug" depending on the answers to the following questions:

1) The program naming convention changed. Was that intentional? Should I use the new convention for things published 11/6/20 and beyond?
2) The version string is inconsistent when compared to the name. Should they match?

**Before (JDK 8 update 272 and below)** 
Name: AdoptOpenJDK JDK with Hotspot 8.0.272.10 (x64)
Version: 8.0.272.10

**After**
Name: AdoptOpenJDK JDK with Hotspot 8u275-b01 (x64)
Version: 8.0.275.1

Observe the program naming convention version changed and does not align with the version string.

**JDK 11**
Name: AdoptOpenJDK JDK with Hotspot 11.0.9.11 (x64)
Version: 11.0.9.11

The latest JDK 11 update 9 continues to use the existing convention. I suspect it might change with a newer version.

**Comment by aahlenst** [comment]
The change was applied after a 200+ messages long discussion on how to fit 11.0.9.1+1 (currently being built and tested) into our current versioning scheme which can only deal with 3 components instead of 4. Because that involves some formula that makes the version number of the MSI even less recognizable than before, it was decided to include the real version number in the name (which is 8u275-b01 for the latest 8u release). 11.0.9.1+1 will have similar properties.
