### ISSUE TITLE
Different Version Numbers for the current JDK 8 hotspot MSI

### ISSUE THREAD

**Issue by Apfelwurm** [AdoptOpenJDK/openjdk-installer#272]
I'm building deployment automation at the moment and i noticed that the current JDK 8 hotspot release has different version numbers in the x86 and the x64 version.

x86: 8.0.275.01
x64: 8.0.275.1

It would be great if the version numbers are the same, since its the same release.

Thanks!

**Comment by douph1** [comment]
@aahlenst this must be looked up into the upstream job I think, all the build numbers are passed as installer job from caller job

https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/create_installer_windows/10068/parameters/
x64  > PRODUCT_BUILD_NUMBER=03

https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/create_installer_windows/10048/parameters/
x86-32 > PRODUCT_BUILD_NUMBER=03

**Comment by douph1** [comment]
@Apfelwurm can you precise where you find this version numbers and on which plateforme (Linux/Mac/Windows (Zip/msi)) ?

**Comment by Apfelwurm** [comment]
Oh, i should have written this in the text as well, the msi packages under Windows are affected.
it can be checked with MS Orca (tool which is included in the Windows SDK) in the Property tables of the MSI.

**Comment by douph1** [comment]
Sorry, this is not PRODUCT_BUILD_NUMBER but 'MSI_PRODUCT_VERSION' wich is used for  ProductVersion
and the last change is from 2020-11-10 13:26:25 +0000 https://github.com/AdoptOpenJDK/openjdk-build/pull/2219

but the x86 OpenJDK8U-jre_x64_windows_hotspot_8u275b01.zip  was generated at 2020-11-09 (before the last change/fix)

I think this is already adressed since https://github.com/AdoptOpenJDK/openjdk-build/pull/2219

Nighlty from 2 December 2020 are good 
x64 8.0.282.3
x32 8.0.282.3

**Comment by douph1** [comment]
inside "release" file 
x86 BUILD_SOURCE="git:47ad2f52" commit from Date:   Sun Nov 8 14:58:00 2020 +0000
x64 BUILD_SOURCE="git:c0a1a87c" commit from Date:   Tue Nov 10 14:54:15 2020 +0000
--
