### ISSUE TITLE
Integration with SDKMan

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-installer#31]
I know the SDKMan folks really wanted to become a potential deployment mechanism for the binaries - http://sdkman.io/ - much discussion etc would be required.

**Comment by marc0der** [comment]
I'd love to help you guys get set up for this. I can arrange for access to our Vendor API so that you can publish your own versions as part of your release build.

We would need to chat about version naming schemes, supported platforms and archive formats though. This is all pretty straightforward stuff and shouldn't hinder us from moving ahead with this.

We can have some initial discussions at Gitter, I've set up a [new channel](https://gitter.im/sdkman/adoptopenjdk) for us to get going.

**Comment by AmauryOrtega** [comment]
I can see that everyone moved to slack. Is it possible to get a summary on how this is going?

**Comment by thekalinga** [comment]
Even I would like to know whether this would be done anytime soon as I also want to move away from zulu

**Comment by marc0der** [comment]
Adopt has been available on sdkman for ages, and is kept up to date by the sdkman community.

**Comment by thekalinga** [comment]
I just did a `sdk ls java` & I see `adoptopenjdk` distribution aswell there. Thanks

**Comment by marc0der** [comment]
We have both hs and j9 variants.

**Comment by thekalinga** [comment]
Can you close this issue in that case. Thanks!
