### ISSUE TITLE
Provide an update-in-place installer

### ISSUE THREAD

**Issue by dougbreaux** [AdoptOpenJDK/openjdk-installer#88]
Discussed with @pshipton

Please consider providing installers (I'm on Windows) that can update an existing JDK in place so that we don't have to manually install a new fix level, point applications at that new location, and manually uninstall the prior fix level.

For instance, I just installed jdk-8.0.212.03-openj9, pointed my Eclipse to use it, and then manually uninstalled jdk-8.0.202.08 (which also didn't even have the "-openj9" in the name either).

Further, having some way to even know there is an updated version available would be nice too. But I could see that being an entirely different feature.

**Comment by karianna** [comment]
@douph1 My understanding is that the very latest installers now do this, is that correct?

@dougbreaux And yes the update notification will need to be an opt-in feature that we develop :-).

**Comment by douph1** [comment]
@dougbreaux 
>Please consider providing installers (I'm on Windows) that can update an existing JDK in place so that we don't have to manually install a new fix level, point applications at that new location, and manually uninstall the prior fix level.

New installer produce since 19 mars handle this ( https://github.com/AdoptOpenJDK/openjdk-installer/pull/74 )
New Windows installer remove old (same java-version/arch/jvm) if newer is installed.
If you rely on PATH for pointing to java.exe or JAVA_HOME it will be transparent.
If you rely on folder, you must update your config as each install use a versionned folder name.
It was not the case for installer 8u202.
Starting with April installer (8u212 and 11.0.3 ) handle it properly, so the next installer in 3 month will replace 8u212 or 11.0.3 (for same arch/jvm)

>which also didn't even have the "-openj9" in the name either

Yes it was not the case in the past but the jvm name hotspot/openj9 will always be included in the folder name
see https://github.com/AdoptOpenJDK/openjdk-installer/pull/73

>Further, having some way to even know there is an updated version available would be nice too. But I could see that being an entirely different feature.

This would be probably handled by https://github.com/AdoptOpenJDK/openjdk-installer/issues/4

**Comment by karianna** [comment]
@dougbreaux Given we have a separate issue for the update notification are you OK for this to be closed?

**Comment by dougbreaux** [comment]
Yeah, sounds like it's the next version where I'll see the old uninstalled and JAVA_HOME updated, so that sounds good. Thanks.
