### ISSUE TITLE
Provide snap support

### ISSUE THREAD

**Issue by julian-alarcon** [AdoptOpenJDK/openjdk-installer#91]
Will be really useful  to support Snap format. It's available on mutliple linux distros.
http://snapcraft.io/

This maybe need the classic approach as AdoptOpenJDK will be used by external projects and may need access to external files.
https://docs.snapcraft.io/snap-confinement/6233

**Comment by aahlenst** [comment]
Considering that "native" packages for most of the major distributions supported by Snap are forthcoming (all except Arch), what exactly would be the benefit of a Snap package? As Snaps are self-contained (and geared towards end-user apps like IntelliJ) anyway, not having AdoptOpenJDK available doesn't hinder other apps from using it. I also have doubts that Snap is popular, even on Ubuntu.

**Comment by nudgegoonies** [comment]
I don't know how common Snap and Flatpak are. Flatpak seems to be more "Standard" because it comes from freedesktop.org. There is also AppImage but i havn't tried this. The good thing is that these packages contain all dependencies besides base dependencies shipped with another package.

The good thing is also the bad thing. Besides general security debates about these package formats and how the integrate in Linux Distributions those packages must be updated much more often because they all ship dependencies. For every security fix in one of the dependencies the whole snap or flatpak has to be updated. There is also the problem about the integration. I don't think that it will be possible to integrate a snap or flatpak with for example the debian "update-java-alternatives".

**Comment by aahlenst** [comment]
I'm closing the issue because there does not seem to be enough demand. Please open a new issue if you think otherwise. In that case add a compelling reason why we should provide Snap packages (see reservations above).
